
Use Library
go
CREATE TABLE [dbo].[Authors]
(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
FirstName VARCHAR(100) NOT NULL,
LastName VARCHAR(100) NOT NULL
)
--go
--CREATE TABLE [dbo].[Books]
--(
--Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
--AuthorId INT NOT NULL,
--FOREIGN KEY (AuthorId) REFERENCES AUTHORS (Id),
--Title VARCHAR(100) NOT NULL,
--PRICE INT,
--PAGES INT
--)
